In [1]:
import numpy as np

In [52]:
x = np.array([1, 2, 3, 4])
y = x*2
print(y)
print("{}\n{}".format(x, y))

[2 4 6 8]
[1 2 3 4]
[2 4 6 8]


In [39]:
z = np.arange(0, 100, 1)
print(z[[4, 5, 6, 7, 8, 9, 10]])

[ 4  5  6  7  8  9 10]


In [59]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
print(a.ndim)
print(a.shape)
print(a.size)

1
(9,)
9


In [67]:
print(a*a)
# print(np.matrix(a)*np.matrix(a))
# print(np.dot(a, a))


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [68]:
b = np.copy(a)
b[b>5]=0

In [69]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 0.5, 0.6])
indicies = np.where(x<5)
x[indicies]
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
index=np.where(x[:,0]>5)
y=np.delete(x,index,axis=1)
print(y)

[[1 2]
 [4 5]
 [7 8]]


In [70]:
np.where?

In [2]:
beehive_data = np.loadtxt('Beehive_data.csv', delimiter=',')

indices = np.where(beehive_data[:,2]>90)
# print(beehive_data)
high_prob=beehive_data[indices]

logd = (high_prob[:,0] + 2.5*high_porb[:,1]+0.17)/5
d = 10**logd
sum_of_dist = 0
for i in d:
    sum_of_dist = sum_of_dist + i
dist_of_cluster= sum_of_dist/d.size
print(dist_of_cluster)

logd_full = (beehive_data[:,0] + 2.5*beehive_data[:,1] + 0.17)/5
d_full = 10**logd_full

NameError: name 'high_porb' is not defined